<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="uib_length" value="0.08" />
<xacro:property name="ee_length" value="0.055" />
<xacro:property name="coxa_length" value="0.05" />
<xacro:property name="motor_diameter" value="0.05" />
<xacro:property name="thigh_offset_y" value="-0.0645" />
<xacro:property name="thigh_offset_z" value="-0.0145" />

<!-- TODO: Update component masses and inertias -->


<xacro:macro name="worms" params="parent *origin">


      <joint name="j_worms_attachment" type="fixed">
        <parent link="${parent}"/>
        <child link="MP_BODY"/>
        <insert_block name="origin" />
      </joint>
      

      <link name="MP_BODY">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 1.57" />
          <!-- <mass value="0.97559947"/> -->
          <mass value="0.01"/>
          <inertia ixx="3.1081800"  ixy="-0.25460189"  ixz="2.0318174" iyy="6.3787776" iyz="0.16417863" izz="5.3316425" />
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="0 0 1.57" />
          <geometry>
            <!--box size="0.102 0.109 0.106" /-->
            <mesh filename="package://worms_description/meshes/pallet.STL"  scale="1 1 1"/>
          </geometry>
          <material name="Red">
            <color rgba="0.2 0.2 0.2 1.0"/>
          </material>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://worms_description/meshes/pallet_coll.STL"  scale="1 1 1"/>
          </geometry>

        </collision>
      </link>


      <gazebo reference="MP_BODY">    
        <material>Gazebo/Red</material>
      </gazebo>

<!-- RPY are set to offset the UIB (first component in leg from the pallet) by 90 degrees then by the angle to match the hexagon -->
<!-- TODO: Replace xyz with calculations based on hexagon diameter -->
    <xacro:leg_l xyz="0.4330 -0.2500 0.0000"  rpy="0 0 ${-0.52 + 1.57}" suffix="rf"/>
    <xacro:leg_l xyz="0.0000 -0.5000 0.0000"  rpy="0 0 ${-1.57 + 1.57}" suffix="rm"/>
    <xacro:leg_l xyz="-0.4330 -0.2500 0.0000"  rpy="0 0 ${-1.57 -1.04 + 1.57}" suffix="rr"/>


    <xacro:leg_l xyz="0.4330 0.2500 0.0000"  rpy="0 0 ${0.52 + 1.57}" suffix="lf"/>
    <xacro:leg_l xyz="0.0000 0.5000 0.0000"  rpy="0 0 ${1.57 + 1.57}" suffix="lm"/>
    <xacro:leg_l xyz="-0.4330 0.2500 0.0000"  rpy="0 0 ${1.57 + 1.04 + 1.57}" suffix="lr"/>

</xacro:macro>





 <xacro:macro name="leg_l" params="xyz rpy suffix">

  <link name="uib_${suffix}">
    <inertial>
      <origin xyz="0 -${uib_length/2} 0" rpy="0 0 0"  />
      <mass value="0.024357719"/>
     <inertia ixx="0.0051411124"  ixy="-0.00057530255"  ixz="-0.000024729049" iyy="0.0081915737" iyz="-0.000019223094" izz="0.0011379812" />
    </inertial>
    <visual>
      <origin xyz="0 -${uib_length/2} 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/UIB.STL"  scale="1 1 1"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.20 0.20 0.20 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 -${uib_length/2} 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/UIB.STL"  scale="1 1 1"/>
      </geometry>
    </collision>
  </link>

  <link name="ee_${suffix}">
    <inertial>
      <origin xyz="0 -${ee_length/2} 0" rpy="0 0 0"  />
      <mass value="0.024357719"/>
     <inertia ixx="0.0051411124"  ixy="-0.00057530255"  ixz="-0.000024729049" iyy="0.0081915737" iyz="-0.000019223094" izz="0.0011379812" />
    </inertial>
    <visual>
      <origin xyz="0 -${ee_length/2} 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/end_effector.STL"  scale="1 1 1"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.20 0.20 0.20 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 -${ee_length/2} 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/end_effector.STL"  scale="1 1 1"/>
      </geometry>
    </collision>
  </link>


  <link name="coxa_${suffix}">
    <inertial>
      <origin xyz="0 -${coxa_length/2} 0" rpy="0 0 0"  />
      <mass value="0.024357719"/>
     <inertia ixx="0.0051411124"  ixy="-0.00057530255"  ixz="-0.000024729049" iyy="0.0081915737" iyz="-0.000019223094" izz="0.0011379812" />
    </inertial>
    <visual>
      <origin xyz="0 -${coxa_length/2} 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/coxa.STL"  scale="1 1 1"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.20 0.20 0.20 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 -${coxa_length/2} 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/coxa.STL"  scale="1 1 1"/>
      </geometry>
    </collision>
  </link>


  <!-- <link name="thigh_${suffix}">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <mass value="0.024357719"/>
     <inertia ixx="0.0051411124"  ixy="-0.00057530255"  ixz="-0.000024729049" iyy="0.0081915737" iyz="-0.000019223094" izz="0.0011379812" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/thigh.STL"  scale="1 1 1"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.20 0.20 0.20 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/thigh.STL"  scale="1 1 1"/>
      </geometry>
    </collision>
  </link>



  <link name="shin_${suffix}">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <mass value="0.024357719"/>
     <inertia ixx="0.0051411124"  ixy="-0.00057530255"  ixz="-0.000024729049" iyy="0.0081915737" iyz="-0.000019223094" izz="0.0011379812" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/shin.STL"  scale="1 1 1"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.20 0.20 0.20 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/shin.STL"  scale="1 1 1"/>
      </geometry>
    </collision>
  </link> -->

  <!-- Joint definitions -->

  <joint name="j_uib_${suffix}" type="fixed">
    <parent link="MP_BODY"/>
    <child link="uib_${suffix}"/>
    <origin xyz="${xyz}" rpy="${rpy}" />
    <axis xyz="1 0 0" />
    <limit effort="2.8" velocity="5.6548668" lower="-2.6179939" upper="2.6179939" />
  </joint>

  <joint name="j_ee_${suffix}" type="fixed">
    <parent link="uib_${suffix}"/>
    <child link="ee_${suffix}"/>
    <origin xyz="0 -${uib_length} 0" rpy="0 0 0" />
    <axis xyz="1 0 0" />
    <limit effort="2.8" velocity="5.6548668" lower="-2.6179939" upper="2.6179939" />
  </joint>

  <joint name="j_coxa_${suffix}" type="revolute">
    <parent link="ee_${suffix}"/>
    <child link="coxa_${suffix}"/>
    <origin xyz="0 -${ee_length + motor_diameter} 0" rpy="0 0 0" />
    <axis xyz="1 0 0" />
    <limit effort="2.8" velocity="5.6548668" lower="-2.6179939" upper="2.6179939" />
  </joint>


<!--   <joint name="j_thigh_${suffix}" type="revolute">
    <parent link="coxa_${suffix}"/>
    <child link="thigh_${suffix}"/>
    <origin xyz="0 0 0" rpy=" 0 3.14159 3.14159" />
    <axis xyz="1 0 0" />
    <limit effort="2.8" velocity="5.6548668" lower="-2.6179939" upper="2.6179939" />
  </joint> -->

  <!-- <joint name="j_shin_${suffix}" type="revolute">
    <parent link="thigh_${suffix}"/>
    <child link="shin_${suffix}"/>
    <origin xyz="0 ${thigh_offset_y} ${thigh_offset_z}" rpy="-1.5707 0 3.14159" />
    <axis xyz="1 0 0" />
    <limit effort="2.8" velocity="5.6548668" lower="-2.6179939" upper="2.6179939" />
  </joint> -->

  <!-- Joint transmission definitions -->

   <!-- <transmission name="t_coxa_${suffix}">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j_coxa_${suffix}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>    
    </joint>
    <actuator name="m_coxa_${suffix}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


   <transmission name="t_thigh_${suffix}">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j_thigh_${suffix}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>    
    </joint>
    <actuator name="m_thigh_${suffix}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


   <transmission name="t_shin_${suffix}">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j_shin_${suffix}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="m_shin_${suffix}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission> -->


<!-- Gazebo material definitions -->

  <gazebo reference="uib_${suffix}">    
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="ee_${suffix}">    
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="coxa_${suffix}">    
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="thigh_${suffix}">    
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="shin_${suffix}">    
    <material>Gazebo/Grey</material>
  </gazebo>

  
</xacro:macro>





</robot>
