<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- World Init Settings -->
<xacro:property name="initial_z_offset" value="1.0" />

<!-- Basic dimensions of WORMS-1 components (in m) -->
<!-- Note: Lengths are reported as distances between consecutive joints (motor axes) -->
<xacro:property name="uib_length" value="0.062373" />
<xacro:property name="ee_length" value="0.062373" />
<xacro:property name="uib_ee_gap_length" value="0.0127" />
<xacro:property name="hip_structure_length" value="0.1397" />
<xacro:property name="coxa_length" value="0.15" />
<xacro:property name="motor_diameter" value="0.098" />
<xacro:property name="thigh_length" value="0.27" />
<xacro:property name="shin_length" value="0.45" />
<xacro:property name="shin_shoe_length" value="0.118" />


<!--  Masses of WORMS-1 components (in kg)-->
<!--  Source: https://docs.google.com/spreadsheets/d/1z4cjFRy08wv40s6Jl9g9mymmIja3-cVj/edit#gid=1875184855-->
<xacro:property name="m_payload" value="15" />
<xacro:property name="m_pallet" value="7" />
<xacro:property name="m_motor" value="0.85" />
<xacro:property name="m_coxa" value="0.5" />
<xacro:property name="m_thigh" value="2" />
<xacro:property name="m_shin" value="6" />
<xacro:property name="m_uib" value="1" />
<xacro:property name="m_ee" value="1" />
<xacro:property name="m_shoe" value="1.52" />


<!-- <xacro:property name="thigh_offset_y" value="-0.0645" />
<xacro:property name="thigh_offset_z" value="-0.0145" /> -->

<!-- TODO: Update component masses and inertias -->
<!-- TODO: Add second ee, uib, and shoe -->
<!-- TODO: Check link length specs -->
<!-- TODO: Add simplified collision meshes -->


<xacro:macro name="worms" params="parent *origin">


      <joint name="j_worms_attachment" type="fixed">
        <parent link="${parent}"/>
        <child link="MP_BODY"/>
        <insert_block name="origin" />
      </joint>
      

      <link name="MP_BODY">
        <inertial>
          <origin xyz="0 0 ${initial_z_offset}" rpy="0 0 1.57" />
	        <mass value="${m_pallet}" />
          <inertia ixx="0.003016"  ixy="0.0"  ixz="0.0" iyy="0.003016" iyz="0.0" izz="0.006014" />
        </inertial>
        <visual>
          <origin xyz="0 0 ${initial_z_offset}" rpy="0 0 1.57" />
          <geometry>
            <!--box size="0.102 0.109 0.106" /-->
            <mesh filename="package://worms_description/meshes/pallet_reduced_new.stl"  scale="1 1 1"/>
          </geometry>
          <material name="Red">
            <color rgba="0.2 0.2 0.2 1.0"/>
          </material>
        </visual>
        <collision>
          <origin xyz="0 0 ${initial_z_offset}" rpy="0 0 1.57" />
          <geometry>
            <mesh filename="package://worms_description/older_parts/pallet.stl"  scale="1 1 1"/>
          </geometry>

        </collision>
      </link>


      <gazebo reference="MP_BODY">    
        <material>Gazebo/Red</material>
      </gazebo>

<!-- RPY are set to offset the UIB (first component in leg from the pallet) by 90 degrees then by the angle to match the hexagon -->
<!-- TODO: Replace xyz with calculations based on hexagon diameter -->
    <xacro:leg_l xyz="0.476 -0.2748 ${initial_z_offset}"  rpy="0 0 ${-0.52 + 1.57}" suffix="rf"/>
    <xacro:leg_l xyz="0.0000 -0.5497 ${initial_z_offset}"  rpy="0 0 ${-1.57 + 1.57}" suffix="rm"/>
    <xacro:leg_l xyz="-0.476 -0.2748 ${initial_z_offset}"  rpy="0 0 ${-1.57 -1.04 + 1.57}" suffix="rr"/>


    <xacro:leg_l xyz="0.476 0.2748 ${initial_z_offset}"  rpy="0 0 ${0.52 + 1.57}" suffix="lf"/>
    <xacro:leg_l xyz="0.0000 0.5497 ${initial_z_offset}"  rpy="0 0 ${1.57 + 1.57}" suffix="lm"/>
    <xacro:leg_l xyz="-0.476 0.2748 ${initial_z_offset}"  rpy="0 0 ${1.57 + 1.04 + 1.57}" suffix="lr"/>

</xacro:macro>



<!-- Leg generation sub-macro -->

 <xacro:macro name="leg_l" params="xyz rpy suffix">

  <link name="hip_structure_${suffix}">
    <inertial>
      <origin xyz="0 -${hip_structure_length + uib_ee_gap_length} 0" rpy="0 0 0"  />
      <mass value="${m_uib}"/>
      <inertia ixx="0.0004167"  ixy="0.0"  ixz="0.0" iyy="0.0007417" iyz="0.0" izz="0.0007417" />
    </inertial>
    <visual>
      <origin xyz="0 -${hip_structure_length + uib_ee_gap_length} 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/hip_structure_reduced.stl"  scale="1 1 1"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.20 0.20 0.20 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 -${hip_structure_length + uib_ee_gap_length} 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/hip_structure_reduced.stl"  scale="1 1 1"/>
      </geometry>
    </collision>
  </link>


  <link name="coxa_${suffix}">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <mass value="${m_coxa + m_motor}"/>
      <inertia ixx="0.0004167"  ixy="0.0"  ixz="0.0" iyy="0.0007417" iyz="0.0" izz="0.0007417" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/motor_coxa.stl"  scale="1 1 1"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.20 0.20 0.20 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/motor_coxa.stl"  scale="1 1 1"/>
      </geometry>
    </collision>
  </link>


  <link name="thigh_${suffix}">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <mass value="${m_thigh + m_motor}"/>
      <inertia ixx="0.0004167"  ixy="0.0"  ixz="0.0" iyy="0.0007417" iyz="0.0" izz="0.0007417" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/motor_thigh.stl"  scale="1 1 1"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.20 0.20 0.20 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/motor_thigh.stl"  scale="1 1 1"/>
      </geometry>
    </collision>
  </link>


  <link name="shin_${suffix}">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <mass value="${m_shin + m_motor}"/>
      <inertia ixx="0.0004167"  ixy="0.0"  ixz="0.0" iyy="0.0007417" iyz="0.0" izz="0.0007417" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/motor_shin_ee_reduced.stl"  scale="1 1 1"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.20 0.20 0.20 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/motor_shin_ee_reduced.stl"  scale="1 1 1"/>
      </geometry>
    </collision>
  </link>

  <link name="shoe_${suffix}">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <mass value="${m_shin + m_motor}"/>
      <inertia ixx="0.0004167"  ixy="0.0"  ixz="0.0" iyy="0.0007417" iyz="0.0" izz="0.0007417" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/ee_shoe_reduced.stl"  scale="1 1 1"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.20 0.20 0.20 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
        <mesh filename="package://worms_description/meshes/ee_shoe_reduced.stl"  scale="1 1 1"/>
      </geometry>
    </collision>
  </link>

  <!-- Joint definitions -->

  <joint name="j_hip_structure_${suffix}" type="fixed">
    <parent link="MP_BODY"/>
    <child link="hip_structure_${suffix}"/>
    <origin xyz="${xyz}" rpy="${rpy}" />
    <axis xyz="1 0 0" />
    <limit effort="2.8" velocity="5.6548668" lower="-2.6179939" upper="2.6179939" />
  </joint>

  <joint name="j_coxa_${suffix}" type="revolute">
    <parent link="hip_structure_${suffix}"/>
    <child link="coxa_${suffix}"/>
    <origin xyz="0 -${hip_structure_length + uib_ee_gap_length} 0" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <limit effort="48" velocity="5.6548668" lower="-2.6179939" upper="2.6179939" />
  </joint>

  <joint name="j_thigh_${suffix}" type="revolute">
    <parent link="coxa_${suffix}"/>
    <child link="thigh_${suffix}"/>
    <origin xyz="0 -${coxa_length} 0" rpy="0.785 0 0" />
    <axis xyz="1 0 0" />
    <limit effort="48" velocity="5.6548668" lower="-2.6179939" upper="2.6179939" />
  </joint>

  <joint name="j_shin_${suffix}" type="revolute">
    <parent link="thigh_${suffix}"/>
    <child link="shin_${suffix}"/>
    <origin xyz="0 -${thigh_length} 0" rpy="0.785 0 0" />
    <axis xyz="1 0 0" />
    <limit effort="48" velocity="5.6548668" lower="-2.6179939" upper="2.6179939" />
  </joint>

  <joint name="j_shoe_${suffix}" type="fixed">
    <parent link="shin_${suffix}"/>
    <child link="shoe_${suffix}"/>
    <origin xyz="0 -${shin_length + shin_shoe_length} 0" rpy="0 0 0" />
    <axis xyz="1 0 0" />
    <limit effort="48" velocity="5.6548668" lower="-2.6179939" upper="2.6179939" />
  </joint>

  <!-- Joint transmission definitions -->

   <transmission name="t_coxa_${suffix}">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j_coxa_${suffix}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>    
    </joint>
    <actuator name="m_coxa_${suffix}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


   <transmission name="t_thigh_${suffix}">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j_thigh_${suffix}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>    
    </joint>
    <actuator name="m_thigh_${suffix}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


   <transmission name="t_shin_${suffix}">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j_shin_${suffix}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="m_shin_${suffix}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


<!-- Gazebo material definitions -->

  <gazebo reference="hip_structure_${suffix}">    
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="coxa_${suffix}">    
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="thigh_${suffix}">    
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="shin_${suffix}">    
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="shoe_${suffix}">    
    <material>Gazebo/Grey</material>
  </gazebo>


<!-- Gazebo gravity setting -->
  <!-- <turnGravityOff>1</turnGravityOff> -->


  
</xacro:macro>





</robot>
