worms:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------


  # HEAD
  j_coxa_lf_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_coxa_lf
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_coxa_rf_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_coxa_rf
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_coxa_lm_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_coxa_lm
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_coxa_rm_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_coxa_rm
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_coxa_lr_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_coxa_lr
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_coxa_rr_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_coxa_rr
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_thigh_lf_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_thigh_lf
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_thigh_rf_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_thigh_rf
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_thigh_lm_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_thigh_lm
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_thigh_rm_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_thigh_rm
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_thigh_lr_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_thigh_lr
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_thigh_rr_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_thigh_rr
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_shin_lf_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_shin_lf
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_shin_rf_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_shin_rf
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_shin_lm_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_shin_lm
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_shin_rm_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_shin_rm
    pid: {p: 100.0, i: 0.01, d: 10.0}


    
  j_shin_lr_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_shin_lr
    pid: {p: 100.0, i: 0.01, d: 10.0}



  j_shin_rr_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_shin_rr
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    

  j_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_pan
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_tilt
    pid: {p: 100.0, i: 0.01, d: 10.0}


  # ARMS

  j_shoulder_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_shoulder_l
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j_high_arm_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_high_arm_l
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j_low_arm_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_low_arm_l
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j_wrist_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_wrist_l
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j_gripper_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_gripper_l
    pid: {p: 100.0, i: 0.01, d: 10.0}


